name = "learnvibe-build"
main = "src/index.tsx"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "learnvibe-db"
database_id = "3d67d43b-4840-4f33-a297-83d94f355a20"
migrations_dir = "drizzle/migrations"

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_dG9waWNhbC1yYWJiaXQtNjAuY2xlcmsuYWNjb3VudHMuZGV2JA"
EMAIL_FROM = "Learn Vibe Build <hello@mail.unforced.dev>"
EMAIL_REPLY_TO = "ag@unforced.org"

# Custom domain
[[routes]]
pattern = "learnvibe.build"
custom_domain = true
