-- Migration 0017 — email_templates table + body_html on email_log
--
-- Schema for issues #22 (email log: view body + resend) and #24 (email
-- template editor with DB-stored templates). Seeds the new email_templates
-- table with the same content the hardcoded TS defaults render so behavior
-- is unchanged at deploy time.
--
-- Generated by scripts/gen-email-templates-seed.ts from
-- src/lib/email-templates-defaults.ts. To update a template's seeded copy,
-- edit the .ts file and re-run the generator.

ALTER TABLE `email_log` ADD COLUMN `body_html` text;
--> statement-breakpoint
CREATE TABLE `email_templates` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`key` text NOT NULL,
	`subject` text NOT NULL,
	`body_markdown` text NOT NULL,
	`variables_json` text DEFAULT '[]' NOT NULL,
	`updated_at` text NOT NULL,
	`updated_by_user_id` integer,
	`active` integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `email_templates_key_unique` ON `email_templates` (`key`);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_received',
  'Application received — Learn Vibe Build',
  '<h2>Thanks for applying, {{firstName}}</h2>
<p>We''ve received your application for Cohort 1. We''ll review it and get back to you soon — typically within a few days.</p>
<div class="email-highlight">
  <p style="margin: 0 0 0.5rem 0;"><strong>One quick step while you wait:</strong></p>
  <p style="margin: 0;">Create your account using <strong>this same email address</strong> — that way when we approve you, your enrollment links automatically and you can jump right in.</p>
</div>
<a href="https://learnvibe.build/sign-up" class="email-cta">Create Your Account</a>
<hr class="email-divider">
<p class="email-muted">You can also check your application status anytime at <a href="https://learnvibe.build/apply/status" style="color: #e8612a; text-decoration: none;">learnvibe.build/apply/status</a>. Questions? Reply to this email or reach out at ag@unforced.dev.</p>',
  '["firstName"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_approved',
  'You''re approved! — Learn Vibe Build Cohort 1',
  '<h2>You''re in, {{firstName}}!</h2>
<p>Your application for Cohort 1 has been approved. We''re excited to have you.</p>
<div class="email-highlight">
  <p><strong>{{tierLabel}}</strong> — {{amountFormatted}}</p>
</div>
<p>Complete your payment to secure your spot:</p>
<a href="{{paymentUrl}}" class="email-cta">Pay {{amountFormatted}} & Enroll →</a>
<hr class="email-divider">
<p class="email-muted">If you haven''t yet, also <a href="https://learnvibe.build/sign-up" style="color: #e8612a; text-decoration: none;">create your account</a> using <strong>this same email address</strong> — that way you can access the cohort site as soon as you''re enrolled. The course starts in April 2026; we''ll send more details as we get closer. Questions? Just reply.</p>',
  '["firstName","tierLabel","amountFormatted","paymentUrl"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_approved_sponsored',
  'You''re in! — Learn Vibe Build Cohort 1',
  '<h2>Welcome, {{firstName}}!</h2>
<p>Great news — your application for Cohort 1 has been approved, and your spot has been sponsored. No payment needed.</p>
<p>Complete your enrollment to get started:</p>
<a href="{{paymentUrl}}" class="email-cta">Complete Enrollment →</a>
<hr class="email-divider">
<p class="email-muted">The course starts in April 2026. We''ll send you details as we get closer. In the meantime, feel free to reply with any questions.</p>',
  '["firstName","paymentUrl"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_rejected',
  'Update on your application — Learn Vibe Build',
  '<h2>Hi {{firstName}},</h2>
<p>Thank you for applying to Learn Vibe Build Cohort 1. After careful consideration, we weren''t able to offer you a spot in this cohort.</p>
<p>This isn''t a reflection of your potential — our cohorts are small and we can only take a limited number of participants each round.</p>
<p>We''d love to see you apply again for a future cohort. We''re always expanding what we offer, and there may be a better fit down the road.</p>
<hr class="email-divider">
<p class="email-muted">If you have any questions, feel free to reply to this email.</p>',
  '["firstName"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_price_changed',
  'Your Cohort 1 pricing has been updated — Learn Vibe Build',
  '<h2>Hi {{firstName}},</h2>
<p>We''ve updated the pricing on your Cohort 1 enrollment.</p>
<div class="email-highlight">
  <p><strong>New price:</strong> {{tierLabel}} — {{newAmountFormatted}}<br>
  <span style="color: #6b7280; font-size: 0.9em;">(was {{oldAmountFormatted}})</span></p>
</div>
<p>If you haven''t paid yet, the updated amount will apply when you do:</p>
<a href="{{paymentUrl}}" class="email-cta">Pay {{newAmountFormatted}} & Enroll →</a>
<hr class="email-divider">
<p class="email-muted">Questions or need a different arrangement? Just reply — cost should never be a barrier.</p>',
  '["firstName","tierLabel","oldAmountFormatted","newAmountFormatted","paymentUrl"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'application_price_changed_sponsored',
  'Your Cohort 1 spot is now sponsored — Learn Vibe Build',
  '<h2>Good news, {{firstName}}!</h2>
<p>We''ve updated your enrollment — your spot in Cohort 1 is now <strong>sponsored</strong>. No payment required.</p>
<p>Complete your enrollment to get started:</p>
<a href="{{paymentUrl}}" class="email-cta">Complete Enrollment →</a>
<hr class="email-divider">
<p class="email-muted">Questions? Reply to this email or reach out at ag@unforced.dev.</p>',
  '["firstName","paymentUrl"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'enrollment_confirmed_no_account',
  'Welcome to {{cohortTitle}} — Learn Vibe Build',
  '<h2>You''re enrolled, {{firstName}}!</h2>
<p>You''re officially part of {{cohortTitle}}. Welcome to the community.</p>
<div class="email-highlight">
  <p><strong>One last step:</strong> Create your account using <strong>this same email address</strong> so you can access the cohort site. Your enrollment will link automatically.</p>
</div>
<a href="https://learnvibe.build/sign-up" class="email-cta">Create Your Account →</a>
<hr class="email-divider">
<p class="email-muted">Already have an account? <a href="https://learnvibe.build/dashboard" style="color: #e8612a; text-decoration: none;">Go to your dashboard</a>.</p>',
  '["firstName","cohortTitle"]',
  (datetime('now')),
  1
);
--> statement-breakpoint
INSERT OR IGNORE INTO `email_templates` (`key`, `subject`, `body_markdown`, `variables_json`, `updated_at`, `active`) VALUES (
  'enrollment_confirmed_has_account',
  'You''re enrolled in {{cohortTitle}} — Learn Vibe Build',
  '<h2>You''re enrolled, {{firstName}}!</h2>
<p>You''re officially part of {{cohortTitle}}. Welcome to the community.</p>
<div class="email-highlight">
  <p><strong>What''s next:</strong> We''ll send you session details as we get closer to the start date. You can access the cohort site anytime via your dashboard.</p>
</div>
<a href="https://learnvibe.build/dashboard" class="email-cta">Go to Your Dashboard →</a>
<hr class="email-divider">
<p class="email-muted">Questions? Just reply to this email.</p>',
  '["firstName","cohortTitle"]',
  (datetime('now')),
  1
);
