// One-shot generator for the email_templates seed SQL.
// Writes to drizzle/migrations/0017_email_templates_and_log_body.sql.
// Run with: npx tsx scripts/gen-email-templates-seed.ts
//
// Why a generator: hand-escaping multi-line HTML strings inside SQL is error-
// prone (every apostrophe must double). This script reads the canonical
// templates from src/lib/email-templates-defaults.ts and emits a consistent
// migration file, so the SQL stays in sync with the TS source-of-truth.

import { writeFileSync } from 'node:fs'
import { DEFAULT_TEMPLATES, TEMPLATE_KEYS } from '../src/lib/email-templates-defaults'

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

const header = `-- Migration 0017 — email_templates table + body_html on email_log
--
-- Schema for issues #22 (email log: view body + resend) and #24 (email
-- template editor with DB-stored templates). Seeds the new email_templates
-- table with the same content the hardcoded TS defaults render so behavior
-- is unchanged at deploy time.
--
-- Generated by scripts/gen-email-templates-seed.ts from
-- src/lib/email-templates-defaults.ts. To update a template's seeded copy,
-- edit the .ts file and re-run the generator.

ALTER TABLE \`email_log\` ADD COLUMN \`body_html\` text;
--> statement-breakpoint
CREATE TABLE \`email_templates\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`key\` text NOT NULL,
\t\`subject\` text NOT NULL,
\t\`body_markdown\` text NOT NULL,
\t\`variables_json\` text DEFAULT '[]' NOT NULL,
\t\`updated_at\` text NOT NULL,
\t\`updated_by_user_id\` integer,
\t\`active\` integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`email_templates_key_unique\` ON \`email_templates\` (\`key\`);
--> statement-breakpoint`

const seedStatements = TEMPLATE_KEYS.map(key => {
  const tpl = DEFAULT_TEMPLATES[key]
  const variables = JSON.stringify(tpl.variables)
  return `INSERT OR IGNORE INTO \`email_templates\` (\`key\`, \`subject\`, \`body_markdown\`, \`variables_json\`, \`updated_at\`, \`active\`) VALUES (
  ${sqlString(key)},
  ${sqlString(tpl.subject)},
  ${sqlString(tpl.bodyMarkdown)},
  ${sqlString(variables)},
  (datetime('now')),
  1
);`
}).join('\n--> statement-breakpoint\n')

const out = `${header}\n${seedStatements}\n`
const path = 'drizzle/migrations/0017_email_templates_and_log_body.sql'
writeFileSync(path, out)
console.error(`wrote ${path} (${out.length} bytes, ${TEMPLATE_KEYS.length} seed rows)`)
